# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\eric6\UI\NotificationFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotificationFrame(object):
    def setupUi(self, NotificationFrame):
        NotificationFrame.setObjectName("NotificationFrame")
        NotificationFrame.resize(400, 80)
        NotificationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        NotificationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        NotificationFrame.setLineWidth(1)
        self.horizontalLayout = QtWidgets.QHBoxLayout(NotificationFrame)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(NotificationFrame)
        self.icon.setMaximumSize(QtCore.QSize(48, 48))
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.heading = QtWidgets.QLabel(NotificationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading.sizePolicy().hasHeightForWidth())
        self.heading.setSizePolicy(sizePolicy)
        self.heading.setMinimumSize(QtCore.QSize(335, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setText("")
        self.heading.setObjectName("heading")
        self.verticalLayout.addWidget(self.heading)
        self.text = QtWidgets.QLabel(NotificationFrame)
        self.text.setMinimumSize(QtCore.QSize(335, 0))
        self.text.setText("")
        self.text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text.setWordWrap(True)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(NotificationFrame)
        QtCore.QMetaObject.connectSlotsByName(NotificationFrame)

    def retranslateUi(self, NotificationFrame):
        pass
