# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\eric6\UI\PythonDisViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PythonDisViewer(object):
    def setupUi(self, PythonDisViewer):
        PythonDisViewer.setObjectName("PythonDisViewer")
        PythonDisViewer.resize(400, 577)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PythonDisViewer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(PythonDisViewer)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.disWidget = QtWidgets.QTreeWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disWidget.sizePolicy().hasHeightForWidth())
        self.disWidget.setSizePolicy(sizePolicy)
        self.disWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.disWidget.setAlternatingRowColors(True)
        self.disWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.disWidget.setAllColumnsShowFocus(True)
        self.disWidget.setObjectName("disWidget")
        self.disWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.disWidget)
        self.currentInfoLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentInfoLabel.setObjectName("currentInfoLabel")
        self.verticalLayout.addWidget(self.currentInfoLabel)
        self.labeledInfoLabel = QtWidgets.QLabel(self.layoutWidget)
        self.labeledInfoLabel.setObjectName("labeledInfoLabel")
        self.verticalLayout.addWidget(self.labeledInfoLabel)
        self.codeInfoWidget = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codeInfoWidget.sizePolicy().hasHeightForWidth())
        self.codeInfoWidget.setSizePolicy(sizePolicy)
        self.codeInfoWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.codeInfoWidget.setAlternatingRowColors(True)
        self.codeInfoWidget.setObjectName("codeInfoWidget")
        self.codeInfoWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(PythonDisViewer)
        QtCore.QMetaObject.connectSlotsByName(PythonDisViewer)

    def retranslateUi(self, PythonDisViewer):
        _translate = QtCore.QCoreApplication.translate
        PythonDisViewer.setWindowTitle(_translate("PythonDisViewer", "Disassembly"))
        self.currentInfoLabel.setText(_translate("PythonDisViewer", "italic: current instruction"))
        self.labeledInfoLabel.setText(_translate("PythonDisViewer", "bold: labeled instruction"))
