# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\eric6\VirtualEnv\VirtualenvInterpreterSelectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VirtualenvInterpreterSelectionDialog(object):
    def setupUi(self, VirtualenvInterpreterSelectionDialog):
        VirtualenvInterpreterSelectionDialog.setObjectName("VirtualenvInterpreterSelectionDialog")
        VirtualenvInterpreterSelectionDialog.resize(550, 118)
        VirtualenvInterpreterSelectionDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(VirtualenvInterpreterSelectionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(VirtualenvInterpreterSelectionDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nameEdit = QtWidgets.QLineEdit(VirtualenvInterpreterSelectionDialog)
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout.addWidget(self.nameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(VirtualenvInterpreterSelectionDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pythonExecPicker = E5PathPicker(VirtualenvInterpreterSelectionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pythonExecPicker.sizePolicy().hasHeightForWidth())
        self.pythonExecPicker.setSizePolicy(sizePolicy)
        self.pythonExecPicker.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pythonExecPicker.setObjectName("pythonExecPicker")
        self.verticalLayout.addWidget(self.pythonExecPicker)
        self.buttonBox = QtWidgets.QDialogButtonBox(VirtualenvInterpreterSelectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VirtualenvInterpreterSelectionDialog)
        self.buttonBox.accepted.connect(VirtualenvInterpreterSelectionDialog.accept)
        self.buttonBox.rejected.connect(VirtualenvInterpreterSelectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VirtualenvInterpreterSelectionDialog)
        VirtualenvInterpreterSelectionDialog.setTabOrder(self.pythonExecPicker, self.nameEdit)

    def retranslateUi(self, VirtualenvInterpreterSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        VirtualenvInterpreterSelectionDialog.setWindowTitle(_translate("VirtualenvInterpreterSelectionDialog", "Add Virtual Environment"))
        self.label_2.setText(_translate("VirtualenvInterpreterSelectionDialog", "Name:"))
        self.label.setText(_translate("VirtualenvInterpreterSelectionDialog", "Enter interpreter for virtual environment:"))
        self.pythonExecPicker.setToolTip(_translate("VirtualenvInterpreterSelectionDialog", "Enter the Python interpreter of the virtual environment"))
from E5Gui.E5PathPicker import E5PathPicker
