# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChildrenForm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildrenForm1(object):
    def setupUi(self, ChildrenForm1):
        ChildrenForm1.setObjectName("ChildrenForm1")
        ChildrenForm1.resize(400, 347)
        self.textEdit = QtWidgets.QTextEdit(ChildrenForm1)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 401, 341))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(ChildrenForm1)
        QtCore.QMetaObject.connectSlotsByName(ChildrenForm1)

    def retranslateUi(self, ChildrenForm1):
        _translate = QtCore.QCoreApplication.translate
        ChildrenForm1.setWindowTitle(_translate("ChildrenForm1", "Form"))
        self.textEdit.setHtml(_translate("ChildrenForm1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我是子窗口内容</p></body></html>"))
