# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\eric6\Preferences\ConfigurationPages\EditorHighlightingStylesSelectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditorHighlightingStylesSelectionDialog(object):
    def setupUi(self, EditorHighlightingStylesSelectionDialog):
        EditorHighlightingStylesSelectionDialog.setObjectName("EditorHighlightingStylesSelectionDialog")
        EditorHighlightingStylesSelectionDialog.resize(400, 500)
        EditorHighlightingStylesSelectionDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorHighlightingStylesSelectionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(EditorHighlightingStylesSelectionDialog)
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.lexersList = QtWidgets.QListWidget(EditorHighlightingStylesSelectionDialog)
        self.lexersList.setAlternatingRowColors(True)
        self.lexersList.setObjectName("lexersList")
        self.verticalLayout.addWidget(self.lexersList)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditorHighlightingStylesSelectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditorHighlightingStylesSelectionDialog)
        self.buttonBox.accepted.connect(EditorHighlightingStylesSelectionDialog.accept)
        self.buttonBox.rejected.connect(EditorHighlightingStylesSelectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditorHighlightingStylesSelectionDialog)

    def retranslateUi(self, EditorHighlightingStylesSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        self.lexersList.setSortingEnabled(True)
